// techLogos.js
import {
  react,
  tailwind,
  js,
  html,
  css,
  sanity,
  vercel,
  wordPress,
  gitHub,
  postman,
  mongodb,
  figma,
  ph,
  ai,
} from "../assets/iconExports/index.js";

export const techLogos = [
  {
    id: 1,
    src: vercel,
    category: "Workflow",
    title: "Vercel",
    href: "https://vercel.com/home",
  },
  {
    id: 2,
    src: react,
    category: "Frontend",
    title: "React",
    href: "https://react.dev",
  },
  {
    id: 3,
    src: tailwind,
    category: "Frontend",
    title: "Tailwind CSS",
    href: "https://tailwindcss.com",
  },
  {
    id: 4,
    src: js,
    category: "Frontend",
    title: "JavaScript",
    href: "https://javascript.info/",
  },
  {
    id: 5,
    src: mongodb,
    category: "Backend",
    title: "MongoDB",
    href: "https://www.mongodb.com/",
  },
  {
    id: 6,
    src: postman,
    category: "Backend",
    title: "Postman",
    href: "https://www.postman.com/",
  },
  {
    id: 7,
    src: html,
    category: "Frontend",
    title: "HTML",
    href: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  {
    id: 8,
    src: css,
    category: "Frontend",
    title: "CSS",
    href: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  {
    id: 9,
    src: sanity,
    category: "cms",
    title: "Sanity",
    href: "https://www.sanity.io/",
  },
  {
    id: 10,
    src: wordPress,
    category: "cms",
    title: "wordPress",
    href: "https://wordpress.org/",
  },
  {
    id: 11,
    src: gitHub,
    category: "Workflow",
    title: "gitHub",
    href: "https://github.com/",
  },
  {
    id: 12,
    src: figma,
    category: "ui-ux",
    title: "figma",
    href: "https://www.figma.com/",
  },
  {
    id: 13,
    src: ph,
    category: "ui-ux",
    title: "Photoshop",
    href: "https://www.adobe.com/products/photoshop.html",
  },
  {
    id: 14,
    src: ai,
    category: "ui-ux",
    title: "illustrator",
    href: "https://www.adobe.com/products/illustrator.html",
  },
];
